apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  master.cnf: |-
    # Apply this config only on the master.
    [mysqld]
    bind-address     = 0.0.0.0
  slave.cnf: |-
    # Apply this config only on slaves.
    [mysqld]
    bind-address     = 0.0.0.0
    super-read-only

