apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  creationTimestamp: null
  name: tenant1
  namespace: default
scheduler:
  name: ""
spec:
  certConfig: {}
  console:
    consoleSecret:
      name: tenant1-console-secret
    image: minio/console:v0.3.14
    metadata:
      creationTimestamp: null
      name: tenant1
    replicas: 1
    resources: {}
  credsSecret:
    name: tenant1-creds-secret
  image: minio/minio:RELEASE.2020-09-26T03-44-56Z
  imagePullSecret: {}
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 1
    timeoutSeconds: 1
  mountPath: /export
  requestAutoCert: true
  serviceName: tenant1-internal-service
  zones:
  - resources: {}
    servers: 1
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaim
      metadata:
        name: minio-tenant1
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 1Gi
      status: {}
    volumesPerServer: 4
status:
  availableReplicas: 0
  currentState: ""

---
apiVersion: v1
data:
  accesskey: MzM0YmE4MDItZTllMy00ZTJjLWI0MGMtNmZlMDhlNGE1MWRk
  secretkey: OGRmZGVjZTItZGM0Zi00NTZlLThjMDEtMDIwOGMzYjcwODYx
kind: Secret
metadata:
  creationTimestamp: null
  name: tenant1-creds-secret
  namespace: default

---
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: ZWIyNmZiODUtOTIxNi00OWUyLWIwMTQtYTVkN2FjOTdhZDdm
  CONSOLE_HMAC_JWT_SECRET: MjFmYjVkMDItNTUwMi00ZDVlLWI2ZmUtYTJiODZmNjYxODJm
  CONSOLE_PBKDF_PASSPHRASE: MzIxYzU4ODYtZjY5Mi00ODAyLTkzNzEtMGNmMmMzZDJhNDA1
  CONSOLE_PBKDF_SALT: NjljYjE2ZTEtMzFmMC00NDhhLWJlYjEtODYxNjZhZWM0M2Q4
  CONSOLE_SECRET_KEY: MTQ5Nzg0NTQtNTBjZC00ZDVmLWFhZjAtMzgxMDU3MTlkYjJm
kind: Secret
metadata:
  creationTimestamp: null
  name: tenant1-console-secret
  namespace: default

